name: Deploy Resume to S3
on:
  push:
    branches:
      - main  # നിങ്ങൾ കോഡ് push ചെയ്യുമ്പോൾ ഇത് പ്രവർത്തിക്കും

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to S3
        run: aws s3 sync . s3://resume-bucket2026 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2 # നിങ്ങളുടെ ബക്കറ്റ് ഒഹായോയിൽ ആയതുകൊണ്ട് ഇത് തന്നെ നൽകുക